"""Public, I/O-free contracts for the b24api client."""

from b24api.contracts.command import (
    Command,
    CommandFailure,
    CommandNotExecuted,
    CommandOutcome,
    CommandOutcomeUnknown,
    CommandSuccess,
    NotExecutedReason,
    partition_command_outcomes,
)
from b24api.contracts.dispatch import BatchDispatch, DeliveryOrder, DirectDispatch, DispatchSpec
from b24api.contracts.json import JsonScalar, JsonValue
from b24api.contracts.policy import (
    ExecutionPolicy,
    IdentityCoercion,
)
from b24api.contracts.reference import (
    Binding,
    ParameterUpdate,
    ReferenceComplete,
    ReferenceEvent,
    ReferenceFailure,
    ReferenceItem,
    ReferenceNotExecuted,
    ReferenceOutcome,
    ReferenceOutcomeUnknown,
    partition_reference_outcomes,
)
from b24api.contracts.report import OperationReport, TerminalState, TraversalAssurance, Violation, ViolationSeverity
from b24api.contracts.request import (
    IdentitySpec,
    ParameterPath,
    ReplaySafety,
    Request,
    RequestLike,
    RequestSpec,
    RequestSummary,
    ResultSelector,
)
from b24api.contracts.response import Response, ResultCollectionShape
from b24api.contracts.stream import OperationStream, PartialResult
from b24api.contracts.traversal import (
    CountedTraversal,
    CursorSpec,
    CursorTraversal,
    KeysetSpec,
    KeysetTraversal,
    OffsetSpec,
    SequentialTraversal,
    TraversalSpec,
)

__all__ = [
    "BatchDispatch",
    "Binding",
    "Command",
    "CommandFailure",
    "CommandNotExecuted",
    "CommandOutcome",
    "CommandOutcomeUnknown",
    "CommandSuccess",
    "CountedTraversal",
    "CursorSpec",
    "CursorTraversal",
    "DeliveryOrder",
    "DirectDispatch",
    "DispatchSpec",
    "ExecutionPolicy",
    "IdentityCoercion",
    "IdentitySpec",
    "JsonScalar",
    "JsonValue",
    "KeysetSpec",
    "KeysetTraversal",
    "NotExecutedReason",
    "OffsetSpec",
    "OperationReport",
    "OperationStream",
    "ParameterPath",
    "ParameterUpdate",
    "PartialResult",
    "ReferenceComplete",
    "ReferenceEvent",
    "ReferenceFailure",
    "ReferenceItem",
    "ReferenceNotExecuted",
    "ReferenceOutcome",
    "ReferenceOutcomeUnknown",
    "ReplaySafety",
    "Request",
    "RequestLike",
    "RequestSpec",
    "RequestSummary",
    "Response",
    "ResultCollectionShape",
    "ResultSelector",
    "SequentialTraversal",
    "TerminalState",
    "TraversalAssurance",
    "TraversalSpec",
    "Violation",
    "ViolationSeverity",
    "partition_command_outcomes",
    "partition_reference_outcomes",
]
