"""Public, I/O-free contracts for the b24api client."""

from b24api.contracts.command import (
    Command,
    CommandFailure,
    CommandNotExecuted,
    CommandOutcome,
    CommandOutcomeUnknown,
    CommandSuccess,
    NotExecutedReason,
    partition_command_outcomes,
)
from b24api.contracts.dispatch import BatchDispatch, DeliveryOrder, DirectDispatch, DispatchSpec
from b24api.contracts.json import JsonScalar, JsonValue
from b24api.contracts.policy import (
    AmbiguityPolicy,
    AmbiguityReason,
    ConsistencyPolicy,
    ExecutionPolicy,
    IdentityCoercion,
    RetryPolicy,
    UnknownRequestAudit,
    UnknownRequestCollector,
)
from b24api.contracts.reference import (
    Binding,
    ParameterUpdate,
    ReferenceComplete,
    ReferenceEvent,
    ReferenceFailure,
    ReferenceItem,
    ReferenceNotExecuted,
    ReferenceOutcome,
    ReferenceOutcomeUnknown,
    partition_reference_outcomes,
)
from b24api.contracts.report import (
    OperationReport,
    PageDispatch,
    PageOutcome,
    PageRecord,
    PageRejectionCode,
    TerminalState,
    TraversalAssurance,
    Violation,
    ViolationSeverity,
)
from b24api.contracts.request import (
    CompositeIdentitySpec,
    IdentityComponent,
    IdentitySpec,
    ParameterPath,
    ReplaySafety,
    Request,
    RequestLike,
    RequestSpec,
    RequestSummary,
    ResultErrorShape,
    ResultErrorSpec,
    ResultSelector,
    TraversalIdentity,
)
from b24api.contracts.response import BinaryEvidence, BinaryResponse, Response, ResultCollectionShape
from b24api.contracts.stream import OperationStream, PartialResult
from b24api.contracts.traversal import (
    CountedTraversal,
    CursorSpec,
    CursorTraversal,
    KeysetSpec,
    KeysetTraversal,
    OffsetContinuation,
    OffsetSpec,
    SequentialTraversal,
    SplitOrderSpec,
    TotalTermination,
    TraversalSpec,
    traversal_control_paths,
)
from b24api.contracts.wire import BodyEncoding, RequestHeaders

__all__ = [
    "AmbiguityPolicy",
    "AmbiguityReason",
    "BatchDispatch",
    "BinaryEvidence",
    "BinaryResponse",
    "Binding",
    "BodyEncoding",
    "Command",
    "CommandFailure",
    "CommandNotExecuted",
    "CommandOutcome",
    "CommandOutcomeUnknown",
    "CommandSuccess",
    "CompositeIdentitySpec",
    "ConsistencyPolicy",
    "CountedTraversal",
    "CursorSpec",
    "CursorTraversal",
    "DeliveryOrder",
    "DirectDispatch",
    "DispatchSpec",
    "ExecutionPolicy",
    "IdentityCoercion",
    "IdentityComponent",
    "IdentitySpec",
    "JsonScalar",
    "JsonValue",
    "KeysetSpec",
    "KeysetTraversal",
    "NotExecutedReason",
    "OffsetContinuation",
    "OffsetSpec",
    "OperationReport",
    "OperationStream",
    "PageDispatch",
    "PageOutcome",
    "PageRecord",
    "PageRejectionCode",
    "ParameterPath",
    "ParameterUpdate",
    "PartialResult",
    "ReferenceComplete",
    "ReferenceEvent",
    "ReferenceFailure",
    "ReferenceItem",
    "ReferenceNotExecuted",
    "ReferenceOutcome",
    "ReferenceOutcomeUnknown",
    "ReplaySafety",
    "Request",
    "RequestHeaders",
    "RequestLike",
    "RequestSpec",
    "RequestSummary",
    "Response",
    "ResultCollectionShape",
    "ResultErrorShape",
    "ResultErrorSpec",
    "ResultSelector",
    "RetryPolicy",
    "SequentialTraversal",
    "SplitOrderSpec",
    "TerminalState",
    "TotalTermination",
    "TraversalAssurance",
    "TraversalIdentity",
    "TraversalSpec",
    "UnknownRequestAudit",
    "UnknownRequestCollector",
    "Violation",
    "ViolationSeverity",
    "partition_command_outcomes",
    "partition_reference_outcomes",
    "traversal_control_paths",
]
