[build-system]
requires = [
    "setuptools>=80.9.0",
    "setuptools-git-versioning>=2.1.0",
    "wheel>=0.45.1",
]
build-backend = "setuptools.build_meta"

[tool.setuptools-git-versioning]
enabled = true

[project]
name = "b24api"
dynamic = ["version"]
description = "Bitrix24 API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx[http2]>=0.28.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
]

[project.scripts]
b24api = "b24api.cli:main"

[tool.setuptools.packages.find]
include = ["b24api*"]

[dependency-groups]
dev = [
    "jsonschema>=4.25.1",
    "mypy>=1.15.0",
    "pytest-asyncio>=1.1.0",
    "pytest-env>=1.1.5",
    "pytest-httpx>=0.35.0",
    "pytest-mock>=3.14.1",
    "ruff>=0.15.5",
    "setuptools>=80.9.0",
    "setuptools-git-versioning>=2.1.0",
    "types-jsonschema>=4.26.0.20260113",
    "wheel>=0.45.1",
]

[tool.ruff]
fix = true
unsafe-fixes = true
line-length = 120
target-version = "py312"

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
select = ["ALL"]
ignore = ["EM", "TRY003"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
no-lines-before = ["standard-library"]
known-third-party = []

[tool.ruff.lint.extend-per-file-ignores]
"*_test.py" = [
    "D100",
    "D103",
    "S101",
    "S311",
]


[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = [
    "h2.*",
]
ignore_missing_imports = true

[tool.pytest.ini_options]
addopts = ["--strict-config", "--strict-markers"]
asyncio_default_fixture_loop_scope = "function"
xfail_strict = true

[tool.pytest_env]
BITRIX24_API_WEBHOOK_URL = "https://bitrix24.com/rest/0/test/"


[tool.coverage.report]
exclude_also = ["if typing.TYPE_CHECKING:"]
