"""§3.12 (C7): the 51-name package root, the ``ROOT_MOVES`` map and the migration it drives.

Test 5 (typing) runs in the ``wheel-typing`` CI job; here only its smoke files are pinned to the map.
"""

from __future__ import annotations
import ast
import importlib
import importlib.util
import re
import warnings
from pathlib import Path

import pytest

import b24api
from b24api import migration
from b24api.migration import PUBLIC_NAMESPACES, ROOT_MOVES, Finding, migration_table, scan, scan_source

ROOT = Path(__file__).resolve().parents[1]
SNAPSHOT_COUNT = 165
MOVED_COUNT = 115
USAGE_EXIT = 2
MIN_CONSUMER_SOURCES = 20
ROOT_NAMES = [
    "Bitrix24",
    "Settings",
    "Request",
    "RouteKind",
    "ReplaySafety",
    "ExecutionPolicy",
    "RetryPolicy",
    "AmbiguityPolicy",
    "DirectDispatch",
    "BatchDispatch",
    "ResultSelector",
    "IdentitySpec",
    "IdentityCoercion",
    "OffsetSpec",
    "OffsetContinuation",
    "TotalTermination",
    "KeysetSpec",
    "AutoKeysetExecution",
    "SequentialKeysetExecution",
    "RangeKeysetExecution",
    "PartitionedKeysetExecution",
    "StableIntegerKeysetContract",
    "BoundedIdentityRange",
    "CursorSpec",
    "CountedTraversal",
    "SequentialTraversal",
    "KeysetTraversal",
    "CursorTraversal",
    "Binding",
    "ParameterPath",
    "ParameterUpdate",
    "PageStopPolicy",
    "PageAdapter",
    "OperationReport",
    "TraversalAssurance",
    "TerminalState",
    "Transport",
    "WireTransport",
    "HttpxTransport",
    "B24ApiError",
    "TransportError",
    "ProtocolError",
    "ApiResponseError",
    "PaginationError",
    "CapabilityError",
    "IncompleteTraversalError",
    "KeysetCapabilityError",
    "BatchFailed",
    "ReferenceFailed",
    "AmbiguousExecutionError",
    "BudgetExceededError",
]
PYTHON_BLOCK = re.compile(r"```python\n(.*?)\n```", re.DOTALL)
TABLE = re.compile(
    r"<!-- ROOT_MOVES table: generated by b24api\.migration\.migration_table\(\); do not edit by hand -->\n"
    r"(?P<table>.*?)<!-- end of ROOT_MOVES table -->",
    re.DOTALL,
)


def _moved(name: str) -> object:
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", DeprecationWarning)
        return getattr(b24api, name)


def test_root_all_is_exactly_the_specified_names() -> None:
    assert sorted(b24api.__all__) == sorted(ROOT_NAMES)


def test_root_and_moves_partition_the_c4cafdd_root() -> None:
    snapshot = set((ROOT / "tests" / "golden" / "root_all_c4cafdd.txt").read_text(encoding="utf-8").split())

    assert len(snapshot) == SNAPSHOT_COUNT
    assert len(ROOT_MOVES) == MOVED_COUNT
    assert not set(b24api.__all__) & set(ROOT_MOVES)
    assert set(b24api.__all__) | set(ROOT_MOVES) == snapshot | {"HttpxTransport"}
    assert set(ROOT_MOVES) <= snapshot


@pytest.mark.parametrize(("name", "package"), sorted(ROOT_MOVES.items()))
def test_each_moved_name_is_the_same_object_in_its_public_package(name: str, package: str) -> None:
    module = importlib.import_module(package)

    assert package in PUBLIC_NAMESPACES
    assert package != "b24api"
    assert name in module.__all__
    assert _moved(name) is getattr(module, name)


def test_root_exports_are_real_attributes_and_moved_names_are_not() -> None:
    assert all(name in vars(b24api) for name in b24api.__all__)
    assert not set(ROOT_MOVES) & set(vars(b24api))
    assert "CommandSuccess" not in dir(b24api)


def test_old_root_import_warns_with_the_new_path_at_the_importing_line(tmp_path: Path) -> None:
    consumer = tmp_path / "old_consumer.py"
    consumer.write_text("from b24api import CommandSuccess as LOADED\n", encoding="utf-8")
    spec = importlib.util.spec_from_file_location("old_consumer", consumer)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)

    with pytest.warns(
        DeprecationWarning, match=r"^b24api\.CommandSuccess moved to b24api\.contracts\.CommandSuccess$"
    ) as record:
        spec.loader.exec_module(module)

    # A package's from-import reads the name twice (importlib's fromlist check, then IMPORT_FROM); both
    # warnings name the consumer's line, so the default filter shows it once.
    assert {(Path(warning.filename), warning.lineno) for warning in record} == {(consumer, 1)}
    assert module.LOADED is importlib.import_module("b24api.contracts").CommandSuccess


def test_attribute_access_warns_for_every_package_kind() -> None:
    for name in ("FrozenJson", "WireResponse", "CompletionGate", "ResponseTooLargeError"):
        with pytest.warns(DeprecationWarning, match=f"b24api.{name} moved to {ROOT_MOVES[name]}.{name}"):
            getattr(b24api, name)


@pytest.mark.parametrize("name", ["NoSuchName", "KeysetSelectionSummary", "migration_table"])
def test_names_outside_the_map_raise_attribute_error_without_a_warning(name: str) -> None:
    with warnings.catch_warnings():
        warnings.simplefilter("error")
        with pytest.raises(AttributeError, match=f"module 'b24api' has no attribute '{name}'"):
            getattr(b24api, name)


def test_program_names_live_only_in_contracts() -> None:
    contracts = importlib.import_module("b24api.contracts")

    assert "KeysetSelectionSummary" in contracts.__all__
    assert "KeysetSelectionSummary" not in ROOT_MOVES


def test_migration_module_is_a_leaf() -> None:
    tree = ast.parse(Path(migration.__file__).read_text(encoding="utf-8"))
    imported = {node.module for node in ast.walk(tree) if isinstance(node, ast.ImportFrom)}
    imported |= {alias.name for node in ast.walk(tree) if isinstance(node, ast.Import) for alias in node.names}

    assert not {module for module in imported if module and module.split(".")[0] == "b24api"}


def test_migration_guide_table_is_generated_from_the_map() -> None:
    guide = (ROOT / "docs" / "migration.md").read_text(encoding="utf-8")
    match = TABLE.search(guide)

    assert match is not None
    assert match["table"] == migration_table()
    assert "python -m b24api.migration" in guide
    rows = migration_table().splitlines()[2:]
    assert len(rows) == MOVED_COUNT
    assert all(
        f"`from {ROOT_MOVES[name]} import {name}`" in row for row, name in zip(rows, _table_names(rows), strict=True)
    )


def _table_names(rows: list[str]) -> list[str]:
    return [row.split("import ", 1)[1].split("`", 1)[0] for row in rows]


SCANNED = """\
import b24api
import b24api as bx
from b24api import Bitrix24, CommandSuccess
from b24api.contracts import FrozenJson

value = b24api.WireResponse
other = bx.CompletionGate
kept = b24api.Request
"""


def test_scanner_reports_root_imports_and_attributes_of_moved_names(tmp_path: Path) -> None:
    path = tmp_path / "consumer.py"

    findings = scan_source(SCANNED, path)

    assert findings == [
        Finding(path, 3, "CommandSuccess"),
        Finding(path, 6, "WireResponse"),
        Finding(path, 7, "CompletionGate"),
    ]
    assert str(findings[0]) == f"{path}:3 b24api.CommandSuccess -> b24api.contracts.CommandSuccess"


def test_scanner_reports_a_wildcard_root_import(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    # A wildcard import follows __all__, which no longer lists the moved names, so CommandSuccess below raises
    # NameError in 3.0; the scanner cannot tell which names the module uses and asks for explicit imports.
    path = tmp_path / "consumer.py"
    path.write_text("from b24api import *\nCommandSuccess\n", encoding="utf-8")

    findings = scan_source(path.read_text(encoding="utf-8"), path)

    assert "CommandSuccess" not in b24api.__all__
    assert findings == [Finding(path, 1, "*")]
    assert str(findings[0]) == f"{path}:1 from b24api import * -> import each name you use explicitly"
    assert migration.main([str(path)]) == 1
    assert capsys.readouterr().out.splitlines() == [str(findings[0])]
    assert scan_source("from b24api.contracts import *\nfrom b24api import Request\n", path) == []


def test_scanner_walks_directories_and_sets_the_exit_code(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    clean = tmp_path / "clean"
    dirty = tmp_path / "dirty" / "nested"
    clean.mkdir()
    dirty.mkdir(parents=True)
    (clean / "ok.py").write_text(
        "from b24api import Request\nfrom b24api.errors import HTTPGatewayError\n", encoding="utf-8"
    )
    (dirty / "old.py").write_text(SCANNED, encoding="utf-8")
    (dirty / "notes.txt").write_text("from b24api import FrozenJson\n", encoding="utf-8")

    assert scan([clean]) == []
    assert migration.main([str(clean)]) == 0
    assert capsys.readouterr().out == ""
    assert migration.main([str(tmp_path)]) == 1
    assert capsys.readouterr().out.splitlines() == [str(finding) for finding in scan([dirty / "old.py"])]
    assert migration.main([]) == USAGE_EXIT
    assert "usage: python -m b24api.migration PATH..." in capsys.readouterr().err


def test_repository_uses_no_deprecated_root_alias() -> None:
    paths = [ROOT / directory for directory in ("b24api", "examples", "tests", "tools")]

    assert [str(finding) for finding in scan(paths)] == []


def _consumer_sources() -> list[tuple[str, str]]:
    sources: list[tuple[str, str]] = []
    for document in [ROOT / "README.md", *sorted((ROOT / "docs").rglob("*.md"))]:
        if "specifications" in document.relative_to(ROOT).parts:
            continue
        blocks = PYTHON_BLOCK.findall(document.read_text(encoding="utf-8"))
        sources.extend((f"{document.relative_to(ROOT)} block {index}", block) for index, block in enumerate(blocks))
    sources.extend(
        (str(path.relative_to(ROOT)), path.read_text(encoding="utf-8"))
        for path in sorted((ROOT / "examples").rglob("*.py"))
    )
    return sources


def _imported_modules(source: str) -> list[str]:
    modules: list[str] = []
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            modules.append(node.module)
        elif isinstance(node, ast.Import):
            modules.extend(alias.name for alias in node.names)
    return [module for module in modules if module.split(".")[0] == "b24api"]


def test_readme_docs_and_examples_import_only_public_namespaces() -> None:
    sources = _consumer_sources()
    leaked = [
        f"{name}: {module}"
        for name, source in sources
        for module in _imported_modules(source)
        if module not in PUBLIC_NAMESPACES
    ]

    assert len(sources) > MIN_CONSUMER_SOURCES
    assert leaked == []
    assert [str(finding) for name, source in sources for finding in scan_source(source, Path(name))] == []


def test_positive_typing_smoke_imports_every_moved_name_from_its_package() -> None:
    smoke = ast.parse((ROOT / "tests" / "typing_smoke" / "moved_names.py").read_text(encoding="utf-8"))
    pairs = sorted(
        (alias.name, node.module or "")
        for node in ast.walk(smoke)
        if isinstance(node, ast.ImportFrom) and (node.module or "").startswith("b24api")
        for alias in node.names
    )

    assert pairs == sorted(ROOT_MOVES.items())


def test_negative_typing_smoke_is_one_old_root_import() -> None:
    smoke = (ROOT / "tests" / "typing_smoke" / "root_alias.txt").read_text(encoding="utf-8")

    assert [line for line in smoke.splitlines() if line and not line.startswith("#")] == [
        "from b24api import CommandSuccess"
    ]


def test_migration_scanner_docstring_states_that_the_package_root_is_imported() -> None:
    import b24api.migration  # noqa: PLC0415 - the module under test

    doc = " ".join((b24api.migration.__doc__ or "").split())
    assert "the check runs even where the rest of the package cannot be imported" not in doc
    assert "still imports the package root first" in doc
